# Generated by Django 4.0.2 on 2022-03-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='hint',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='point_value',
            field=models.IntegerField(default=0, max_length=7),
        ),
    ]
