# Generated by Django 4.0.2 on 2022-04-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_quesmodel_hint_quesmodel_point_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='timer',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
